import type {
  Approval,
  Expense,
  FlightCalendarEntry,
  Notification,
  Policy,
  TravelRequest,
  User,
} from "./types";

export const USERS: User[] = [
  {
    userId: "U001",
    name: "Pragnesh",
    email: "pragnesh@o2h.com",
    department: "Admin",
    role: "admin",
    reportingManager: "-",
  },
  {
    userId: "U002",
    name: "Siddhi",
    email: "siddhi@o2h.com",
    department: "Chemistry",
    role: "employee",
    reportingManager: "Rajeshree",
  },
  {
    userId: "U003",
    name: "Rajeshree",
    email: "rajeshree@o2h.com",
    department: "Chemistry",
    role: "hod",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U004",
    name: "Muskan",
    email: "muskan@o2h.com",
    department: "Biology",
    role: "employee",
    reportingManager: "Swaroop",
  },
  {
    userId: "U005",
    name: "Swaroop",
    email: "swaroop@o2h.com",
    department: "Biology",
    role: "hod",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U006",
    name: "Chandrakant",
    email: "chandrakant@o2h.com",
    department: "Finance",
    role: "finance",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U007",
    name: "Devanshi",
    email: "devanshi@o2h.com",
    department: "HR",
    role: "employee",
    reportingManager: "Fulkaran",
  },
  {
    userId: "U008",
    name: "Fulkaran",
    email: "fulkaran@o2h.com",
    department: "BD",
    role: "manager",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U009",
    name: "Nehal",
    email: "nehal@o2h.com",
    department: "Chemistry",
    role: "employee",
    reportingManager: "Rajeshree",
  },
  {
    userId: "U010",
    name: "Kavya",
    email: "kavya@o2h.com",
    department: "DMPK",
    role: "employee",
    reportingManager: "Priya",
  },
  {
    userId: "U011",
    name: "Ritesh",
    email: "ritesh@o2h.com",
    department: "ADL",
    role: "employee",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U012",
    name: "Priya",
    email: "priya@o2h.com",
    department: "DMPK",
    role: "hod",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U013",
    name: "Aakash",
    email: "aakash@o2h.com",
    department: "ADL",
    role: "employee",
    reportingManager: "Pragnesh",
  },
];

export const DEPARTMENT_APPROVERS: Record<string, string> = {
  Chemistry: "HOD Chemistry",
  Biology: "HOD Biology",
  DMPK: "HOD DMPK",
  ADL: "ADL Head",
  General: "Admin",
  Finance: "Finance Head",
  HR: "HR Head",
  BD: "Business Director",
};

export const TRAVEL_REQUESTS: TravelRequest[] = [
  // FY27 Q1 (Apr–Jun 2026)
  {
    requestId: "TR001",
    userId: "U002",
    userName: "Siddhi",
    from: "Ahmedabad",
    to: "London",
    country: "UK",
    startDate: "2026-06-10",
    endDate: "2026-06-15",
    purpose: "Client Meeting",
    clientName: "PharmaCo UK",
    department: "Chemistry",
    estimatedCost: 285000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: true,
    status: "pending_hod",
    fy: "FY27",
    createdAt: "2026-05-01",
  },
  {
    requestId: "TR003",
    userId: "U003",
    userName: "Rajeshree",
    from: "Ahmedabad",
    to: "Frankfurt",
    country: "Germany",
    startDate: "2026-05-22",
    endDate: "2026-05-25",
    purpose: "Vendor Meeting",
    department: "Chemistry",
    estimatedCost: 165000,
    hotelRequired: true,
    visaRequired: false,
    forexRequired: true,
    advanceRequired: false,
    status: "approved",
    fy: "FY27",
    createdAt: "2026-04-28",
  },
  // FY27 Q2 (Jul–Sep 2026)
  {
    requestId: "TR002",
    userId: "U004",
    userName: "Muskan",
    from: "Mumbai",
    to: "Boston",
    country: "USA",
    startDate: "2026-07-02",
    endDate: "2026-07-09",
    purpose: "Conference",
    clientName: "BioSummit",
    department: "Biology",
    estimatedCost: 420000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: false,
    status: "pending_finance",
    fy: "FY27",
    createdAt: "2026-05-05",
  },
  {
    requestId: "TR008",
    userId: "U002",
    userName: "Siddhi",
    from: "Ahmedabad",
    to: "Chicago",
    country: "USA",
    startDate: "2026-08-10",
    endDate: "2026-08-17",
    purpose: "BD Meeting",
    clientName: "LifeScience Corp",
    department: "Chemistry",
    estimatedCost: 310000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: true,
    status: "approved",
    fy: "FY27",
    createdAt: "2026-07-10",
  },
  // FY27 Q3 (Oct–Dec 2026)
  {
    requestId: "TR004",
    userId: "U010",
    userName: "Kavya",
    from: "Ahmedabad",
    to: "Singapore",
    country: "Singapore",
    startDate: "2026-10-05",
    endDate: "2026-10-12",
    purpose: "Research Partnership",
    clientName: "BioPharma SG",
    department: "DMPK",
    estimatedCost: 195000,
    hotelRequired: true,
    visaRequired: false,
    forexRequired: true,
    advanceRequired: false,
    status: "approved",
    fy: "FY27",
    createdAt: "2026-09-10",
  },
  {
    requestId: "TR005",
    userId: "U012",
    userName: "Priya",
    from: "Ahmedabad",
    to: "Paris",
    country: "France",
    startDate: "2026-11-18",
    endDate: "2026-11-22",
    purpose: "Scientific Summit",
    department: "DMPK",
    estimatedCost: 255000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: true,
    status: "pending_hod",
    fy: "FY27",
    createdAt: "2026-10-20",
  },
  {
    requestId: "TR009",
    userId: "U004",
    userName: "Muskan",
    from: "Mumbai",
    to: "Seoul",
    country: "South Korea",
    startDate: "2026-12-08",
    endDate: "2026-12-13",
    purpose: "Collaboration Meeting",
    department: "Biology",
    estimatedCost: 230000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: false,
    status: "pending_finance",
    fy: "FY27",
    createdAt: "2026-11-05",
  },
  // FY27 Q4 (Jan–Mar 2027)
  {
    requestId: "TR006",
    userId: "U011",
    userName: "Ritesh",
    from: "Mumbai",
    to: "Berlin",
    country: "Germany",
    startDate: "2027-01-15",
    endDate: "2027-01-20",
    purpose: "Lab Visit",
    department: "ADL",
    estimatedCost: 175000,
    hotelRequired: true,
    visaRequired: false,
    forexRequired: true,
    advanceRequired: false,
    status: "approved",
    fy: "FY27",
    createdAt: "2026-12-18",
  },
  {
    requestId: "TR010",
    userId: "U013",
    userName: "Aakash",
    from: "Ahmedabad",
    to: "Tokyo",
    country: "Japan",
    startDate: "2027-02-20",
    endDate: "2027-02-26",
    purpose: "Tech Transfer",
    department: "ADL",
    estimatedCost: 320000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: true,
    status: "pending_admin",
    fy: "FY27",
    createdAt: "2027-01-22",
  },
  // FY28 Q1 (Apr–Jun 2027)
  {
    requestId: "TR007",
    userId: "U013",
    userName: "Aakash",
    from: "Ahmedabad",
    to: "London",
    country: "UK",
    startDate: "2027-04-10",
    endDate: "2027-04-16",
    purpose: "Partnership Review",
    clientName: "Pharma UK Ltd",
    department: "ADL",
    estimatedCost: 290000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: true,
    status: "pending_admin",
    fy: "FY28",
    createdAt: "2027-03-15",
  },
  {
    requestId: "TR011",
    userId: "U003",
    userName: "Rajeshree",
    from: "Ahmedabad",
    to: "Amsterdam",
    country: "Netherlands",
    startDate: "2027-05-12",
    endDate: "2027-05-17",
    purpose: "Research Collaboration",
    department: "Chemistry",
    estimatedCost: 245000,
    hotelRequired: true,
    visaRequired: false,
    forexRequired: true,
    advanceRequired: false,
    status: "approved",
    fy: "FY28",
    createdAt: "2027-04-10",
  },
];

export const APPROVALS: Approval[] = [
  {
    approvalId: "A001",
    requestId: "TR001",
    approver: "Rajeshree",
    approverRole: "HOD Chemistry",
    status: "pending",
    date: "2026-05-02",
  },
  {
    approvalId: "A002",
    requestId: "TR002",
    approver: "Chandrakant",
    approverRole: "Finance",
    status: "pending",
    date: "2026-05-06",
  },
];

export const EXPENSES: Expense[] = [
  {
    expenseId: "E001",
    userId: "U003",
    userName: "Rajeshree",
    category: "Flight",
    amount: 89000,
    currency: "INR",
    fy: "FY27",
    department: "Chemistry",
    status: "finance_review",
    tripRef: "TR003",
    uploadedAt: "2026-05-20",
  },
  {
    expenseId: "E002",
    userId: "U002",
    userName: "Siddhi",
    category: "Hotel",
    amount: 45000,
    currency: "INR",
    fy: "FY27",
    department: "Chemistry",
    status: "uploaded",
    uploadedAt: "2026-05-18",
  },
  {
    expenseId: "E003",
    userId: "U004",
    userName: "Muskan",
    category: "Meals",
    amount: 3200,
    currency: "INR",
    fy: "FY27",
    department: "Biology",
    status: "approved",
    uploadedAt: "2026-05-10",
  },
];

export const FLIGHT_CALENDAR: FlightCalendarEntry[] = [
  {
    user: "Siddhi",
    userId: "U002",
    flightDate: "2026-06-10",
    returnDate: "2026-06-15",
    airline: "British Airways",
    pnr: "BA7X92K",
    country: "UK",
    purpose: "Client Meeting",
    department: "Chemistry",
    status: "pending",
  },
  {
    user: "Muskan",
    userId: "U004",
    flightDate: "2026-07-02",
    returnDate: "2026-07-09",
    airline: "Emirates",
    pnr: "EK4M21P",
    country: "USA",
    purpose: "Conference",
    department: "Biology",
    status: "pending",
  },
  {
    user: "Rajeshree",
    userId: "U003",
    flightDate: "2026-05-22",
    returnDate: "2026-05-25",
    airline: "Lufthansa",
    pnr: "LH9K44T",
    country: "Germany",
    purpose: "Vendor Meeting",
    department: "Chemistry",
    status: "confirmed",
  },
  {
    user: "Kavya",
    userId: "U010",
    flightDate: "2026-10-05",
    returnDate: "2026-10-12",
    airline: "Singapore Airlines",
    pnr: "SQ3K91V",
    country: "Singapore",
    purpose: "Research Partnership",
    department: "DMPK",
    status: "confirmed",
  },
  {
    user: "Siddhi",
    userId: "U002",
    flightDate: "2026-08-10",
    returnDate: "2026-08-17",
    airline: "United Airlines",
    pnr: "UA5M88R",
    country: "USA",
    purpose: "BD Meeting",
    department: "Chemistry",
    status: "confirmed",
  },
  {
    user: "Ritesh",
    userId: "U011",
    flightDate: "2027-01-15",
    returnDate: "2027-01-20",
    airline: "Lufthansa",
    pnr: "LH7P23Q",
    country: "Germany",
    purpose: "Lab Visit",
    department: "ADL",
    status: "pending",
  },
  {
    user: "Muskan",
    userId: "U004",
    flightDate: "2026-12-08",
    returnDate: "2026-12-13",
    airline: "Korean Air",
    pnr: "KE9L55W",
    country: "South Korea",
    purpose: "Collaboration Meeting",
    department: "Biology",
    status: "pending",
  },
  {
    user: "Priya",
    userId: "U012",
    flightDate: "2026-11-18",
    returnDate: "2026-11-22",
    airline: "Air France",
    pnr: "AF2T76X",
    country: "France",
    purpose: "Scientific Summit",
    department: "DMPK",
    status: "pending",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "N1",
    type: "approval",
    title: "Approval Pending",
    message: "Siddhi's UK trip (TR001) awaits your approval.",
    read: false,
    createdAt: "2026-05-19T09:00:00",
  },
  {
    id: "N2",
    type: "alert",
    title: "Visa Expiry Alert",
    message: "Muskan's US visa expires in 45 days.",
    read: false,
    createdAt: "2026-05-18T14:30:00",
  },
  {
    id: "N3",
    type: "trip",
    title: "Trip Approved",
    message: "Rajeshree's Frankfurt trip has been approved.",
    read: true,
    createdAt: "2026-05-15T11:00:00",
  },
  {
    id: "N4",
    type: "reminder",
    title: "Expense Pending",
    message: "2 reimbursements pending for FY27.",
    read: false,
    createdAt: "2026-05-17T08:00:00",
  },
];

export const POLICIES: Policy[] = [
  {
    id: "P1",
    name: "Economy Class Default",
    category: "Flight",
    limit: "Business only > 6hr international",
    description: "Default economy for domestic and short-haul international.",
  },
  {
    id: "P2",
    name: "Hotel Budget",
    category: "Hotel",
    limit: "₹8,000/night domestic, $150/night international",
    description: "Pre-approved limits by city tier.",
  },
  {
    id: "P3",
    name: "Meal Allowance",
    category: "Meals",
    limit: "₹1,500/day domestic, $75/day international",
    description: "Receipts required above ₹500.",
  },
  {
    id: "P4",
    name: "Forex Advance",
    category: "Forex",
    limit: "Max 70% of estimated trip cost",
    description: "Advance released after finance approval.",
  },
];

export const ANALYTICS = {
  org: {
    totalCost: 4120000,
    totalTrips: 67,
    totalTravelers: 36,
    avgTripCost: 61493,
    monthlySpend: 412000,
    budget: 5500000,
    actual: 4120000,
  },
  byCountry: [
    { country: "UK", spend: 1020000 },
    { country: "USA", spend: 1280000 },
    { country: "Germany", spend: 540000 },
    { country: "Singapore", spend: 390000 },
    { country: "France", spend: 510000 },
    { country: "India", spend: 380000 },
  ],
  byDepartment: [
    { department: "Chemistry", spend: 980000 },
    { department: "Biology", spend: 1120000 },
    { department: "DMPK", spend: 580000 },
    { department: "ADL", spend: 420000 },
    { department: "General", spend: 180000 },
    { department: "Finance", spend: 210000 },
    { department: "HR", spend: 185000 },
    { department: "BD", spend: 350000 },
  ],
  topTravelers: [
    { name: "Muskan", trips: 8, cost: 620000 },
    { name: "Siddhi", trips: 7, cost: 540000 },
    { name: "Rajeshree", trips: 5, cost: 390000 },
    { name: "Kavya", trips: 4, cost: 310000 },
  ],
  aiInsights: [
    "UK travel spend is 12% above FY27 budget — consider consolidating Q3 client visits.",
    "3 duplicate Ahmedabad–London routes detected in June — bundle bookings for ~8% savings.",
    "DMPK department travel has grown 40% vs FY26 — review budget allocation for FY28.",
    "Chemistry department has 2 pending approvals > 5 days — escalate to reduce delays.",
  ],
};
