import type {
  Approval,
  Expense,
  FlightCalendarEntry,
  Notification,
  Policy,
  TravelRequest,
  User,
} from "./types";

export const USERS: User[] = [
  {
    userId: "U001",
    name: "Pragnesh",
    email: "pragnesh@o2h.com",
    department: "Admin",
    role: "admin",
    reportingManager: "-",
  },
  {
    userId: "U002",
    name: "Siddhi",
    email: "siddhi@o2h.com",
    department: "Chemistry",
    role: "employee",
    reportingManager: "Rajeshree",
  },
  {
    userId: "U003",
    name: "Rajeshree",
    email: "rajeshree@o2h.com",
    department: "Chemistry",
    role: "hod",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U004",
    name: "Muskan",
    email: "muskan@o2h.com",
    department: "Biology",
    role: "employee",
    reportingManager: "Swaroop",
  },
  {
    userId: "U005",
    name: "Swaroop",
    email: "swaroop@o2h.com",
    department: "Biology",
    role: "hod",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U006",
    name: "Chandrakant",
    email: "chandrakant@o2h.com",
    department: "Finance",
    role: "finance",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U007",
    name: "Devanshi",
    email: "devanshi@o2h.com",
    department: "HR",
    role: "employee",
    reportingManager: "Fulkaran",
  },
  {
    userId: "U008",
    name: "Fulkaran",
    email: "fulkaran@o2h.com",
    department: "BD",
    role: "manager",
    reportingManager: "Pragnesh",
  },
  {
    userId: "U009",
    name: "Nehal",
    email: "nehal@o2h.com",
    department: "Chemistry",
    role: "employee",
    reportingManager: "Rajeshree",
  },
];

export const DEPARTMENT_APPROVERS: Record<string, string> = {
  Chemistry: "HOD Chemistry",
  Biology: "HOD Biology",
  Finance: "Finance Head",
  HR: "HR Head",
  BD: "Business Director",
};

export const TRAVEL_REQUESTS: TravelRequest[] = [
  {
    requestId: "TR001",
    userId: "U002",
    userName: "Siddhi",
    from: "Ahmedabad",
    to: "London",
    country: "UK",
    startDate: "2026-06-10",
    endDate: "2026-06-15",
    purpose: "Client Meeting",
    clientName: "PharmaCo UK",
    department: "Chemistry",
    estimatedCost: 285000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: true,
    status: "pending_hod",
    fy: "FY27",
    createdAt: "2026-05-01",
  },
  {
    requestId: "TR002",
    userId: "U004",
    userName: "Muskan",
    from: "Mumbai",
    to: "Boston",
    country: "USA",
    startDate: "2026-07-02",
    endDate: "2026-07-09",
    purpose: "Conference",
    clientName: "BioSummit",
    department: "Biology",
    estimatedCost: 420000,
    hotelRequired: true,
    visaRequired: true,
    forexRequired: true,
    advanceRequired: false,
    status: "pending_finance",
    fy: "FY27",
    createdAt: "2026-05-05",
  },
  {
    requestId: "TR003",
    userId: "U003",
    userName: "Rajeshree",
    from: "Ahmedabad",
    to: "Frankfurt",
    country: "Germany",
    startDate: "2026-05-22",
    endDate: "2026-05-25",
    purpose: "Vendor Meeting",
    department: "Chemistry",
    estimatedCost: 165000,
    hotelRequired: true,
    visaRequired: false,
    forexRequired: true,
    advanceRequired: false,
    status: "approved",
    fy: "FY27",
    createdAt: "2026-04-28",
  },
];

export const APPROVALS: Approval[] = [
  {
    approvalId: "A001",
    requestId: "TR001",
    approver: "Rajeshree",
    approverRole: "HOD Chemistry",
    status: "pending",
    date: "2026-05-02",
  },
  {
    approvalId: "A002",
    requestId: "TR002",
    approver: "Chandrakant",
    approverRole: "Finance",
    status: "pending",
    date: "2026-05-06",
  },
];

export const EXPENSES: Expense[] = [
  {
    expenseId: "E001",
    userId: "U003",
    userName: "Rajeshree",
    category: "Flight",
    amount: 89000,
    currency: "INR",
    fy: "FY27",
    department: "Chemistry",
    status: "finance_review",
    tripRef: "TR003",
    uploadedAt: "2026-05-20",
  },
  {
    expenseId: "E002",
    userId: "U002",
    userName: "Siddhi",
    category: "Hotel",
    amount: 45000,
    currency: "INR",
    fy: "FY27",
    department: "Chemistry",
    status: "uploaded",
    uploadedAt: "2026-05-18",
  },
  {
    expenseId: "E003",
    userId: "U004",
    userName: "Muskan",
    category: "Meals",
    amount: 3200,
    currency: "INR",
    fy: "FY27",
    department: "Biology",
    status: "approved",
    uploadedAt: "2026-05-10",
  },
];

export const FLIGHT_CALENDAR: FlightCalendarEntry[] = [
  {
    user: "Siddhi",
    userId: "U002",
    flightDate: "2026-06-10",
    returnDate: "2026-06-15",
    airline: "British Airways",
    pnr: "BA7X92K",
    country: "UK",
    purpose: "Client Meeting",
    department: "Chemistry",
    status: "pending",
  },
  {
    user: "Muskan",
    userId: "U004",
    flightDate: "2026-07-02",
    returnDate: "2026-07-09",
    airline: "Emirates",
    pnr: "EK4M21P",
    country: "USA",
    purpose: "Conference",
    department: "Biology",
    status: "pending",
  },
  {
    user: "Rajeshree",
    userId: "U003",
    flightDate: "2026-05-22",
    returnDate: "2026-05-25",
    airline: "Lufthansa",
    pnr: "LH9K44T",
    country: "Germany",
    purpose: "Vendor Meeting",
    department: "Chemistry",
    status: "confirmed",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "N1",
    type: "approval",
    title: "Approval Pending",
    message: "Siddhi's UK trip (TR001) awaits your approval.",
    read: false,
    createdAt: "2026-05-19T09:00:00",
  },
  {
    id: "N2",
    type: "alert",
    title: "Visa Expiry Alert",
    message: "Muskan's US visa expires in 45 days.",
    read: false,
    createdAt: "2026-05-18T14:30:00",
  },
  {
    id: "N3",
    type: "trip",
    title: "Trip Approved",
    message: "Rajeshree's Frankfurt trip has been approved.",
    read: true,
    createdAt: "2026-05-15T11:00:00",
  },
  {
    id: "N4",
    type: "reminder",
    title: "Expense Pending",
    message: "2 reimbursements pending for FY27.",
    read: false,
    createdAt: "2026-05-17T08:00:00",
  },
];

export const POLICIES: Policy[] = [
  {
    id: "P1",
    name: "Economy Class Default",
    category: "Flight",
    limit: "Business only > 6hr international",
    description: "Default economy for domestic and short-haul international.",
  },
  {
    id: "P2",
    name: "Hotel Budget",
    category: "Hotel",
    limit: "₹8,000/night domestic, $150/night international",
    description: "Pre-approved limits by city tier.",
  },
  {
    id: "P3",
    name: "Meal Allowance",
    category: "Meals",
    limit: "₹1,500/day domestic, $75/day international",
    description: "Receipts required above ₹500.",
  },
  {
    id: "P4",
    name: "Forex Advance",
    category: "Forex",
    limit: "Max 70% of estimated trip cost",
    description: "Advance released after finance approval.",
  },
];

export const ANALYTICS = {
  org: {
    totalCost: 2845000,
    totalTrips: 47,
    totalTravelers: 28,
    avgTripCost: 60532,
    monthlySpend: 412000,
    budget: 3500000,
    actual: 2845000,
  },
  byCountry: [
    { country: "UK", spend: 820000 },
    { country: "USA", spend: 1100000 },
    { country: "Germany", spend: 380000 },
    { country: "India", spend: 545000 },
  ],
  byDepartment: [
    { department: "Chemistry", spend: 980000 },
    { department: "Biology", spend: 1120000 },
    { department: "Finance", spend: 210000 },
    { department: "HR", spend: 185000 },
    { department: "BD", spend: 350000 },
  ],
  topTravelers: [
    { name: "Muskan", trips: 8, cost: 620000 },
    { name: "Siddhi", trips: 6, cost: 485000 },
    { name: "Rajeshree", trips: 5, cost: 390000 },
  ],
  aiInsights: [
    "UK travel spend is 12% above FY27 budget — consider consolidating Q3 client visits.",
    "3 duplicate Ahmedabad–London routes detected in June — bundle bookings for ~8% savings.",
    "Muskan is a frequent international traveler — negotiate corporate fare with preferred airline.",
    "Chemistry department has 2 pending approvals > 5 days — escalate to reduce delays.",
  ],
};
